### ISSUE TITLE
Cargo.toml workspace package fields

### ISSUE THREAD

**Issue by melMass** [jbolda/covector#267]
Hi,

A quite useful feature of cargo workspace is to share fields between crates, either [packages](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table) or [dependencies](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) might particularly concern covector as it seems it's not able to resolve these:

- *./Cargo.toml*:
	```toml
	[workspace.dependencies]
	anyhow = "1.0"
	```
- *./crates/server/Cargo.toml*
	```toml
	[dependencies]
	anyhow = { workspace = true }
	```

Giving the following error on `covector init` in the root of my mono repo: 

```ruby
Cannot destructure property 'version' of 'parsedTOML.package' as it is undefined.

Effection:
  - task generator [127]
  - task generator function [9]
  - all count=61 generator function [8]
  - task generator [6]
  - task generator [5]
  - task generator [4]
  - start generator function [3]
  ```
